apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
spec:
  
  selector:
    matchLabels:
      app: my-nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: my-nginx
    spec:
      imagePullSecrets: 
      - name: tks-sandbox
      containers:
      - name: my-nginx
        image: tcr.tks.trueidc.com/sandbox-private/my-nginx
 