apiVersion: apps/v1
kind: Deployment
metadata:
  name: kob
spec:
  selector:
    matchLabels:
      app: kob
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kob
    spec:
      containers:
      - name: kob
        image: nginx:1.23.1
        resources:
          limits:
            memory: 200Mi
            cpu: 20m              
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
spec:
  selector:
    matchLabels:
      app: my-nginx
  replicas: 2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: my-nginx
    spec:
      containers:
      - name: my-nginx
        image: nginx:1.23.1
        resources:
          limits:
            memory: 200Mi
            cpu: 2m
      affinity:     
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - kob
              topologyKey: zone
              namespaces:
                - ""
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - kob2
              topologyKey: zone
        # podAntiAffinity:
        #   requiredDuringSchedulingIgnoredDuringExecution:
        #     - labelSelector:
        #         matchExpressions:
        #           - key: app
        #             operator: In
        #             values:
        #               - my-nginx 
        #       topologyKey: kubernetes.io/hostname  