apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
spec:  
  selector:
    matchLabels:
      app: my-nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: my-nginx
    spec:
      imagePullSecrets: 
      - name: tksdemo
      initContainers:
      - name: init-myservice
        image: busybox:1.28
        command: ['sh', '-c', "echo testing"]
      containers:
      - name: my-nginx
        image: my-nginx
 