apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  
  - name: nginx
    resources:
      limits:
        cpu: 100m
        memory: 200Mi
    image: nginx:1.14.2
    env:
      - name: ROOT_PASSWORD 
        value: "1"
    ports:
    - containerPort: 80