#k8s  ?  => 1.25  batch/v1beta1
#batch/v1,1.21 =>
#v1beta1 ,<=1.20
apiVersion: batch/v1

kind: CronJob
metadata:
  name: para
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      backoffLimit: 6
      completions: 4
      parallelism: 2
      template:
        spec:
          containers:
          - name: hello
            image: busybox:1.28
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - echo Hello from the Kubernetes cluster;sleep 10
          restartPolicy: Never # or OnFailure
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  suspend: true