#k8s  ?  => 1.25  batch/v1beta1
#batch/v1,1.21 =>
#v1beta1 ,<=1.20
apiVersion: batch/v1beta1

kind: CronJob
metadata:
  name: para
spec:
  schedule: "* * * * *" 
  jobTemplate:
    spec:
      backoffLimit: 2
      completions: 1
      parallelism: 1
      template:
        spec:
          containers:
          - name: hello
            image: busybox:1.28
            imagePullPolicy: IfNotPresent
            command:
            - echo
            - hlex
            # - /bin/sh
            # - -c
            # - echo Hello from the Kubernetes cluster;sleep 10
          restartPolicy: OnFailure # or OnFailure
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  suspend: false