apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
spec:
  
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: my-nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: my-nginx
    spec:
      # restartPolicy : Never
      containers:
      - name: my-nginx
        image: nginx:1.23.1
        
---
apiVersion: v1
kind: Service
metadata:
  name: my-nginx
  labels:
    app: my-nginx
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: my-nginx
---
apiVersion: 'networking.k8s.io/v1'
kind: 'Ingress'
metadata:
    labels:
        app: my-nginx
    name: my-nginx
spec:
    ingressClassName: nginx    
    rules:
      - host: 'my-nginx.1j44pm75z4o0b.dev.nxcp.trueidc.com'
        http:
            paths:
              - backend:
                    service:
                        name: my-nginx
                        port:
                            number: 80
                path: '/'
                pathType: 'Prefix'
