apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
spec:
  selector:
    matchLabels:
      app: my-nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: my-nginx
    spec:
      volumes:
        - configMap:
            name: hello-cm
            items:
              - key: hello.html
                path: hello2.html
          name: hellodir
      containers:
      - name: my-nginx
        image: nginx
        volumeMounts:
          - mountPath: /usr/share/nginx/html/hello2.html
            name: hellodir
            subPath: hello2.html


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-cm
data:
  hello.html: "hello ja"
  bye.html: "bye ja"
---


# apiVersion: v1
# data:
#   grafana.ini: "MQo="
# kind: Secret
# metadata:
#   name: example-secret