apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
spec:
  selector:
    matchLabels:
      app: my-nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: my-nginx
    spec:
      volumes:
        - secret:
            secretName: hello-secret
            items:
            - key: a.html
              path: folder1/./a.html
          name: hellodir
      containers:
      - name: my-nginx
        image: nginx
        volumeMounts:
          - mountPath: /usr/share/nginx/html/hello
            name: hellodir
---


apiVersion: v1
data:
  a.html: "MQo="
kind: Secret
metadata:
  name: hello-secret